### ISSUE TITLE
How to send a javascript array variable to the vision block

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#430]
Hi everyone

I'm getting the following error when trying to assign a javascript array variable to the vision block

```
itemsArray=["nothing selected", "item1", "item2", "item3"]
vision_step('items = ' + itemsArray)

vision begin

selected = select("Please select an item from the list", options = items)
tagui_text = open('tagui.sikuli/tagui_sikuli.txt','w')
tagui_text.write(str(selected)); tagui_text.close()
vision finish
vision_result = fetch_sikuli_text()

echo vision_result
```
Sikulix log

```
[error] Error caused by: Traceback (most recent call last):
  File "C:\tagui\tagui.sikuli\tagui.py", line 417, in <module>
    intent_result_value = parse_intent(tagui_intent)
  File "C:\tagui\tagui.sikuli\tagui.py", line 367, in parse_intent
    return vision_intent(script_line)
  File "C:\tagui\tagui.sikuli\tagui.py", line 293, in vision_intent
    exec(params,globals())
SyntaxError: ("no viable alternative at input 'selected'", ('<string>', 1, 16, 'items = nothing selected,item1,item2,item3\n'))

IDE terminated: returned: 1
```
Thank you in advance for your support

**Comment by kensoh** [comment]
This is an interesting use case.

Oh the vision_step() function can only send strings or numbers over to SikuliX. As the inherent JS data structure in TagUI cannot be directly sent to SikuliX's Python environment.

Some ideas to explore would be sending item by item using vision_step, then do post processing using vision_step to combine the variables into a data structure in Python. Or maybe use ask step to ask user for inputs in TagUI first, before sending that info to SikuliX for visual automation.

**Comment by muratcim** [comment]
thanks for your reply kensoh

Solved my problem as follows. I'm sharing it to help

```
itemsArray = ["nothing selected", "item1", "item2", "item3"]

itemsArrayString = itemsArray.join(",")

vision_step('itemsArray = "' + itemsArrayString + '"')

vision begin
items = itemsArray.split(",")
selected = select("Please select an item from the list", options = items)
tagui_text = open('tagui.sikuli/tagui_sikuli.txt','w')
tagui_text.write(str(selected)); tagui_text.close()
vision finish
vision_result = fetch_sikuli_text()

echo vision_result
```
